name: Promote heroku environment

on:
  workflow_call:
    inputs:
      app_name:
        description: 'heroku app name'
        required: true
        type: string
    secrets:
      api_key:
        description: 'heroku api key'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.api_key }}
          heroku_app_name: ""
          heroku_email: "swindsor@gmail.com"
          justlogin: true
      - run: heroku pipelines:promote -a ${{ inputs.app_name }}

