name: Promote heroku environment

on:
  workflow_call:
    inputs:
      app_name:
        description: 'heroku app name'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ""
          heroku_email: "scott@reflective.co"
          justlogin: true
      - run:
        heroku pipelines:promote -a ${{inputs.app_name}}

